EXPERIMENT_NAME: CNN LST Classification
DATASETS:
  TRAIN:
    EVENTS: /home/ir-riqu1/rds/rds-iris-ip007/ir-riqu1/Prod5-parquets/output_tiny/events
    TELESCOPES: /home/ir-riqu1/rds/rds-iris-ip007/ir-riqu1/Prod5-parquets/output_tiny/telescopes
    FOLDER: null
  VALIDATION:
    EVENTS: /home/ir-riqu1/rds/rds-iris-ip007/ir-riqu1/Prod5-parquets/output_tiny/events
    TELESCOPES: /home/ir-riqu1/rds/rds-iris-ip007/ir-riqu1/Prod5-parquets/output_tiny/telescopes
    FOLDER: null
  TEST:
    EVENTS: null
    TELESCOPES: null
    FOLDER: null
  AGGREGATION:
    IGNORE_PARTICLE_TYPES: [ electron ]
MODEL:
  DEVICE: cuda
  ARCHITECTURE:
    NAME: CNN
    KWARGS:
    - [hexconv, False]
    - [num_classes, 2]
    - [conv_kernel_sizes, [5, 3, 3, 3]]
    - [dense_layer_units, [128, 64]]
  RECONSTRUCTION_MODE: SINGLE
  TASK: CLASSIFICATION
  TELESCOPES:
  - LST
  WEIGHTS: null
INPUT:
  IMAGE_CHANNELS:
    - image
    - peak_time
    - image_mask
  TELESCOPE_FEATURES:
    - pos_x
    - pos_y
SOLVER:
  BATCH_SIZE: 64
  LOSS:
    CLASS_NAME: SparseCategoricalCrossentropy
    CONFIG: []
  OPTIMIZER:
    CLASS_NAME: Adam
    CONFIG:
      - [amsgrad, True]
  EPOCHS: 10
OUTPUT:
  MAPPER:
    NAME: OnevsAllClassification
METRICS:
  CLASSIFICATION: [ SparseCategoricalAccuracy ]
