EXPERIMENT_NAME: CNN LST VGG mod3 20 Epochs Classification
DATASETS:
  TRAIN:
    EVENTS: /home/ir-riqu1/rds/rds-iris-ip007/ir-riqu1/Prod5-parquets/output_ten_splitted/train_events.parquet
    TELESCOPES: /home/ir-riqu1/rds/rds-iris-ip007/ir-riqu1/Prod5-parquets/output_ten_splitted/train_telescopes.parquet
    FOLDER: null
  VALIDATION:
    EVENTS: /home/ir-riqu1/rds/rds-iris-ip007/ir-riqu1/Prod5-parquets/output_ten_splitted/validation_events.parquet
    TELESCOPES: /home/ir-riqu1/rds/rds-iris-ip007/ir-riqu1/Prod5-parquets/output_ten_splitted/validation_telescopes.parquet
    FOLDER: null
  TEST:
    EVENTS: null
    TELESCOPES: null
    FOLDER: null
  AGGREGATION:
    IGNORE_PARTICLE_TYPES: [ electron ]
MODEL:
  DEVICE: cuda
  ARCHITECTURE:
    NAME: CustomVGG_mod3
    KWARGS:
    - [num_classes, 2]
  RECONSTRUCTION_MODE: SINGLE
  TASK: CLASSIFICATION
  TELESCOPES:
  - LST
  WEIGHTS: null
INPUT:
  IMAGE_CHANNELS:
    - image
    - peak_time
    - image_mask
  TELESCOPE_FEATURES:
    - pos_x
    - pos_y
SOLVER:
  BATCH_SIZE: 128
  LOSS:
    CLASS_NAME: SparseCategoricalCrossentropy
    CONFIG: []
  OPTIMIZER:
    CLASS_NAME: Adam
    CONFIG:
      - [amsgrad, True]
  EPOCHS: 20
OUTPUT:
  MAPPER:
    NAME: OnevsAllClassification
METRICS:
  CLASSIFICATION: [ SparseCategoricalAccuracy ]
