EXPERIMENT_NAME: CNN LST Classification
DATASETS:
  TRAIN:
    EVENTS: null
    TELESCOPES: null
    FOLDER: null
  VALIDATION:
    EVENTS: null
    TELESCOPES: null
    FOLDER: null
  TEST:
    EVENTS: null
    TELESCOPES: null
    FOLDER: null
  AGGREGATION:
    IGNORE_PARTICLE_TYPES: [ electron ]
MODEL:
  DEVICE: cuda
  ARCHITECTURE:
    NAME: CNN
    KWARGS:
    - [num_classes, 2]
  RECONSTRUCTION_MODE: SINGLE
  TASK: CLASSIFICATION
  TELESCOPES:
  - LST
  WEIGHTS: null
INPUT:
  IMAGE_CHANNELS:
    - image
    - peak_time
    - image_mask
  TELESCOPE_FEATURES:
    - pos_x
    - pos_y
SOLVER:
  BATCH_SIZE: 64
  LOSS:
    CLASS_NAME: SparseCategoricalCrossentropy
    CONFIG: []
  OPTIMIZER:
    CLASS_NAME: Adam
    CONFIG:
      - [amsgrad, True]
  EPOCHS: 10
OUTPUT:
  MAPPER:
    NAME: OnevsAllClassification
METRICS:
  CLASSIFICATION: [ SparseCategoricalAccuracy ]
