_BASE_: ../base_simple_regression.yml
EXPERIMENT_NAME: Random Forest LST REGRESSION
DATASETS:
  TRAIN:
    EVENTS: /home/asuka/projects/gerumo2/tools/output/splits/train_events.parquet
    TELESCOPES: /home/asuka/projects/gerumo2/tools/output/splits/train_telescopes.parquet
    FOLDER: null
  VALIDATION:
    EVENTS: /home/asuka/projects/gerumo2/tools/output/splits/validation_events.parquet
    TELESCOPES: /home/asuka/projects/gerumo2/tools/output/splits/validation_telescopes.parquet
    FOLDER: null
  TEST:
    EVENTS: null
    TELESCOPES: null
    FOLDER: null
GENERATOR:
  NAME: OneBatchMonoGenerator
MODEL:
  ARCHITECTURE:
    NAME: RandomForest
    KWARGS:
      - [n_estimators, 150]
      - [criterion, squared_error]
      - [max_depth, null]
      - [min_samples_split, 2]
      - [min_samples_leaf, 1]
      - [min_weight_fraction_leaf, 0]
      - [max_features, 3]
      - [max_leaf_nodes, null]
      - [min_impurity_decrease, 0]
      - [bootstrap, True]
      - [oob_score, True]
      - [n_jobs, -1]
      - [ccp_alpha, 0]
      - [max_samples, null]
  TELESCOPES: 
  - LST 
INPUT:
  MAPPER:
    NAME: SimpleSquareImage
  IMAGE_CHANNELS: []
  TELESCOPE_FEATURES: 
  - hillas_intensity
  - hillas_x
  - hillas_y
  - hillas_r
  - hillas_phi
  - hillas_length
  - hillas_length_uncertainty
  - hillas_width
  - hillas_width_uncertainty
  - hillas_psi
  - hillas_skewness
  - hillas_kurtosis
