_BASE_: ../base_single_regression.yml
MODEL:
  DEVICE: cuda
  ARCHITECTURE:
    NAME: UmonneModel
    KWARGS:
    - ['hexconv', False]
    - ['num_targets', 2]
    - ['conv_kernel_sizes', [5, 3, 3, 3]]
    - ['dense_layer_units', [64, 64]]
INPUT:
  MAPPER:
    NAME: SimpleSquareImage
  IMAGE_CHANNELS:
    - image
    - peak_time
    - image_mask
  TELESCOPE_FEATURES:
    - pos_x
    - pos_y
SOLVER:
  BASE_LR: 0.001
  BATCH_SIZE: 8
  LOSS:
    CLASS_NAME: sparse_nd_crossentropy
    CONFIG: []
  OPTIMIZER:
    CLASS_NAME: SGD
    CONFIG:
      - [momentum, 0.0]
      - [nesterov, false]
  CYCLICAL_LR:
    ENABLE: True
    FACTOR: 2
    MAX_LR: 0.1
    SCALE_FN: fixed_decay