_BASE_: ../base_single_regression.yml
MODEL:
  DEVICE: cuda
  ARCHITECTURE:
    NAME: UmonneModel
    KWARGS:
    - [hexconv, false]
    - [num_targets, 2]
    - [conv_kernel_sizes, [5, 3, 3]]
    - [conv_channels,  [64, 128, 128]]
    - [last_channels, 256]
    - [layer_norm, false]
    - [dense_layer_units, [128, 128, 128]]
    - [normalize_charge, true]
    - [time_peak_max, true]
    - [apply_mask, true]
INPUT:
  MAPPER:
    NAME: SimpleSquareImage
  IMAGE_CHANNELS:
    - image
    - peak_time
    - image_mask
  TELESCOPE_FEATURES:
    - pos_x
    - pos_y
SOLVER:
  BASE_LR: 0.0001
  BATCH_SIZE: 64
  LOSS:
    CLASS_NAME: sparse_nd_crossentropy
    CONFIG:
      - [l2_smoothing, 10.0]
  OPTIMIZER:
    CLASS_NAME: SGD
    CONFIG:
      - [momentum, 0.01]
      - [nesterov, true]
  CYCLICAL_LR:
    ENABLE: True
    FACTOR: 2
    MAX_LR: 0.1
    SCALE_FN: fixed_decay