EXPERIMENT_NAME: UMONNE LST Regression
DATASETS:
  TRAIN:
    EVENTS: /home/asuka/projects/gerumo2/tools/output/splits/train_events.parquet
    TELESCOPES: /home/asuka/projects/gerumo2/tools/output/splits/train_telescopes.parquet
    FOLDER: null
  VALIDATION:
    EVENTS: /home/asuka/projects/gerumo2/tools/output/splits/validation_events.parquet
    TELESCOPES: /home/asuka/projects/gerumo2/tools/output/splits/validation_telescopes.parquet
    FOLDER: null
  TEST:
    EVENTS: null
    TELESCOPES: null
    FOLDER: null
MODEL:
  DEVICE: cuda
  ARCHITECTURE:
    NAME: UmonneModel
    KWARGS:
    - ['hexconv', False]
    - ['num_targets', 2]
    - ['conv_kernel_sizes', [5, 3, 3, 3]]
    - ['dense_layer_units', [64, 64]]
  RECONSTRUCTION_MODE: SINGLE
  TASK: REGRESSION
  TELESCOPES:
  - LST
  WEIGHTS: null
INPUT:
  MAPPER:
    NAME: SimpleSquareImage
  IMAGE_CHANNELS:
    - image
    - peak_time
    - image_mask
  TELESCOPE_FEATURES:
    - pos_x
    - pos_y
OUTPUT:
  MAPPER:
    NAME: SimpleRegression
  REGRESSION:
    TARGETS:
      - true_az
      - true_alt
SOLVER:
  BATCH_SIZE: 8
  LOSS:
    CLASS_NAME: sparse_nd_crossentropy
    CONFIG: []
  OPTIMIZER:
    CLASS_NAME: Adam
    CONFIG:
      - [amsgrad, True]
